# yaml 配置实例
version: '3'  # 本文件遵循的compose版本
services:   # 所有服务
  service_backend:
    build: .  # 使用该目录下的Dockerfile构建的镜像，此处为本目录
    ports:
      - "80:80" # 主机端口：容器端口
      - "${BACKEND_PORT:-80}:80" # 表示命令行启动容器时设置BACKEND_PORT，若不设置，则为默认值80.
    links:  # 表示在容器之间创建网络，进行通信。 links & depends_on 通常只配置一个。
      - service_redis
    depends_on: #   docker compose会按照依赖关系启动容器
      - service_redis
    environment: # 设置容器内部的环境变量
      REDIS_URL: ${REDIS_URL:-http://redis:5000/redis}
  service_frontend:
    depends_on:
      - service_backend
      - service_redis
    links:
      - service_backend
  service_redis:
    image: redis:alpine # 指定容器运行的镜像，会从dockerHub拉取
    expose:
      - "5000" #  暴露容器内部端口，不映射到主机，相当于仅供其他内部服务（通过links连接）调用


